### ISSUE TITLE
Cannot use CurveTracer on 2.0.0rc3

### ISSUE THREAD

**Issue by krillin666** [arc-instruments/arc1_pyqt#1]
Hello,

I have arc1pyqt installed through pip. After loading the *CurveTracer* module and clicking on any of the *Apply to ...* dialogues ,the program crashes with the following error in the console:

` QLayout: Attempting to add QLayout "" to CT_LIVE "", which already has a layout` 

Thank you!

**Comment by foucault** [comment]
Hello, thank you for your report. There is a known issue with the current rc3 release and CurveTracer which should be fixed in the latest git revisions. Install [git](https://git-scm.org) and try re-installing arc1_pyqt with `pip install git+https://github.com/arc-instruments/arc1_pyqt`.

That being said the program should not crash at that point (the warning can be safely ignored) even on rc3, just the CurveTracer module refusing to load. Please ensure that you are running the [latest firmware](https://www.arc-instruments.co.uk/products/arc-one/), and that you install arc1_pyqt on a clean virtual environment. Additionally, please mention the platform you are running arc1_pyqt on. On Windows make sure you have the [mbed serial port drivers](https://os.mbed.com/handbook/Windows-serial-configuration) installed.

**Comment by krillin666** [comment]
I'm using Fedora 37 and installed it on a new conda environment

**Comment by henriquenunez** [comment]
Same issue here, here is a more complete error log
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QLayout: Attempting to add QLayout "" to CT_LIVE "", which already has a layout
Traceback (most recent call last):
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/arc1pyqt/ControlWidgets/prog_panel_widget.py", line 97, in addPanel
    widget = topKlass()
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/arc1pyqt/ProgPanels/CurveTracer.py", line 132, in __init__
    self.initUI()
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/arc1pyqt/ProgPanels/CurveTracer.py", line 146, in initUI
    self.liveWindow = CT_LIVE(short=True)
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/arc1pyqt/ProgPanels/CT_LIVE.py", line 130, in __init__
    self.initialise_variables()
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/arc1pyqt/ProgPanels/CT_LIVE.py", line 401, in initialise_variables
    self.pens.append(pg.mkPen({'color':'F00', 'width':3}))
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/pyqtgraph/functions.py", line 369, in mkPen
    return mkPen(**arg)
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/pyqtgraph/functions.py", line 384, in mkPen
    color = mkColor(color)
  File "/home/hhlinu/my_py38/lib/python3.8/site-packages/pyqtgraph/functions.py", line 272, in mkColor
    raise ValueError(f"Unable to convert {c} to QColor")
ValueError: Unable to convert F00 to QColor

```

Seems like there is an incorrect color string somewhere. I will try to dig into it.
